# Generated by Django 4.1.13 on 2025-12-22 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(db_column='employee_id', default='EMP-001', max_length=255, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('user_role', models.IntegerField(choices=[(1, 'super_admin'), (2, 'admin'), (3, 'manager'), (4, 'report_handler'), (5, 'sales_manager'), (6, 'user')], default=6)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('experience', models.FloatField(db_column='yers_exper', default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_details',
                'managed': True,
            },
        ),
    ]
