# Generated by Django 4.1.13 on 2025-12-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfodetails',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='userinfodetails',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
