# Generated by Django 4.1.13 on 2025-12-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angApp', '0002_userinfodetails_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.IntegerField(db_column='parent_id', default=0, max_length=100)),
                ('deleted', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'tbl_category',
                'managed': (True,),
            },
        ),
    ]
