# Generated by Django 4.1.13 on 2025-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angApp', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
