# Generated by Django 4.1.13 on 2025-12-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angApp', '0004_alter_category_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='meta_description',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
