# Generated by Django 4.1.13 on 2025-12-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angApp', '0005_rename_title_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='slug_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
